# Generated by Django 4.2.2 on 2023-06-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=100, verbose_name="Команда")),
                ("man", models.TextField(verbose_name="Сотрудник")),
            ],
        ),
    ]
