# Generated by Django 4.2.2 on 2023-06-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leader", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="man", new_name="employee",
        ),
    ]
